name: Deploy to GitHub-Pages
on:
   push:
     branches: ["main"]
jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     permissions:
        id-token: write
     steps:
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
           node-version: 14.15.5
       - name: Checkout
         uses: actions/checkout@v3
         with:
           persist-credentials: false
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
          # Upload entire repository
           path: '.'
       - name: Install dependencies
         run: npm i
       - name: Build project
         run: npm run build
       - name: Deploy
         uses: actions/deploy-pages@v4
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           folder: ./build
           branch: gh-pages
           single-commit: true
